name: Build Windows Executable

on:
  release:
    types: [published]

jobs:
  build-windows:
    name: Build Windows executable
    runs-on: windows-latest
    permissions:
      contents: write # Required to upload release assets

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Using '3.x' for consistency with pypi publish workflow

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install . # Install the package itself and its dependencies

      - name: Build executable with PyInstaller
        run: pyinstaller --onefile --name tinycoder run_tinycoder.py

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/tinycoder.exe
          asset_name: tinycoder.exe
          asset_content_type: application/vnd.microsoft.portable-executable