name: Build macOS Executable

on:
  release:
    types: [published]

jobs:
  build-macos:
    name: Build macOS executable
    runs-on: macos-latest
    permissions:
      contents: write # Required to upload release assets

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install . # Install the package itself and its dependencies

      - name: Build executable with PyInstaller
        run: pyinstaller --onefile --name tinycoder_macos run_tinycoder.py

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/tinycoder_macos
          asset_name: tinycoder_macos
          asset_content_type: application/octet-stream