name: CI - Unit Tests and Coverage

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main
      - master

jobs:
  test:
    name: Unit tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install . coverage

      - name: Run unit tests with coverage
        run: |
          coverage run -m unittest -v
          coverage report -m

      - name: Generate coverage XML
        if: always()
        run: coverage xml -o coverage.xml

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ runner.os }}
          path: coverage.xml
          if-no-files-found: error